title: scratch3-reverse-sound
hero_image: images/banner.png
description: scratch3-reverse-sound description
version: 4
listed: false
copyedit: false
last_tested: "2021-06-08"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
